@DotNetStarterProjectTemplate.Api_HostAddress = https://localhost:7225

GET {{DotNetStarterProjectTemplate.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{DotNetStarterProjectTemplate.Api_HostAddress}}/api/things
Accept: application/json

###
