name: Build + Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore DotNetStarterProjectTemplate.sln

    - name: Build
      run: dotnet build DotNetStarterProjectTemplate.sln --no-restore

    - name: Test
      run: |
        dotnet dev-certs https --trust
        dotnet test DotNetStarterProjectTemplate.sln --no-build --verbosity normal
