name: Build + Test
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore DotNetStarterProjectTemplate.slnx

    - name: Build
      run: dotnet build DotNetStarterProjectTemplate.slnx --no-restore

    - name: Test
      run: |
        dotnet dev-certs https --trust
        dotnet test DotNetStarterProjectTemplate.slnx --no-build --verbosity normal
